
/// <summary>
/// I am a class that represent the link between a char and it integer in the context of the standard scratch to warcraft.
/// </summary>

public class ScratchToWarcrafUTF8 {
    public char m_char;
    public int m_integerValue;
    public string m_description;

    public ScratchToWarcrafUTF8() {   }

    public ScratchToWarcrafUTF8(char character, int integerValue, string description)
    {
        m_char = character;
        m_integerValue = integerValue;
        m_description = description;
    }



    public static void TryFind(int integer, out bool found , out char character) { 
    
        TryFind(integer, out found, out ScratchToWarcrafUTF8 foundValue);
        if (found)
            character = foundValue.m_char;
        else
            character = ' ';
    }
    public static void TryFind(int integer, out bool found, out ScratchToWarcrafUTF8 foundValue) { 
    
        found = false;
        foundValue = null;
        foreach(var utf in UTF8)
        {
            if (utf == null)
                continue;
            if (utf.m_integerValue == integer)
            {
                found = true;
                foundValue = utf;
                break;
            }
        }
    }


    public static void TryFind(char character, out bool found, out int  foundValue)
    {
        found = false;
        TryFind(character, out found, out ScratchToWarcrafUTF8 foundValueUTF8);
        if (found)
            foundValue = foundValueUTF8.m_integerValue;
        else
            foundValue = 0;
    }
    public static void TryFind(char character, out bool found, out ScratchToWarcrafUTF8 foundValue)
    {
        found = false;
        foundValue = null;
        foreach (var utf in UTF8)
        {
            if (utf == null)
                continue;
            if (utf.m_char == character)
            {
                found = true;
                foundValue = utf;
                break;
            }
        }
    }
    public static string MainCharWithLetters= "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789~!@#$%^&*()_-+={}[]|\\:;\"'<>,.?/.";
    public static string MainChar = "~!@#$%^&*()_-+={}[]|\\:;\"'<>,.?/.";
    public static ScratchToWarcrafUTF8[] UTF8 = new ScratchToWarcrafUTF8[] {
new ScratchToWarcrafUTF8(' '  ,4032  ,"SPACE                                                 "),
new ScratchToWarcrafUTF8('!'  ,4033   ,"EXCLAMATION MARK                                      "),
new ScratchToWarcrafUTF8('"'  ,4034   ,"QUOTATION MARK                                        "),
new ScratchToWarcrafUTF8('#'  ,4035   ,"NUMBER SIGN                                           "),
new ScratchToWarcrafUTF8('$'  ,4036   ,"DOLLAR SIGN                                           "),
new ScratchToWarcrafUTF8('%'  ,4037   ,"PERCENT SIGN                                          "),
new ScratchToWarcrafUTF8('&'  ,4038   ,"AMPERSAND                                             "),
new ScratchToWarcrafUTF8('\''  ,4039   ,"APOSTROPHE                                           "),
new ScratchToWarcrafUTF8('('  ,4040   ,"LEFT PARENTHESIS                                      "),
new ScratchToWarcrafUTF8(')'  ,4041   ,"RIGHT PARENTHESIS                                     "),
new ScratchToWarcrafUTF8('*'  ,4042   ,"ASTERISK                                              "),
new ScratchToWarcrafUTF8('+'  ,4043   ,"PLUS SIGN                                             "),
new ScratchToWarcrafUTF8(','  ,4044   ,"COMMA                                                 "),
new ScratchToWarcrafUTF8('-'  ,4045   ,"HYPHEN-MINUS                                          "),
new ScratchToWarcrafUTF8('.'  ,4046   ,"FULL STOP                                             "),
new ScratchToWarcrafUTF8('/'  ,4047   ,"SOLIDUS                                               "),
new ScratchToWarcrafUTF8('0'  ,4048   ,"DIGIT ZERO                                            "),
new ScratchToWarcrafUTF8('1'  ,4049   ,"DIGIT ONE                                             "),
new ScratchToWarcrafUTF8('2'  ,4050   ,"DIGIT TWO                                             "),
new ScratchToWarcrafUTF8('3'  ,4051   ,"DIGIT THREE                                           "),
new ScratchToWarcrafUTF8('4'  ,4052   ,"DIGIT FOUR                                            "),
new ScratchToWarcrafUTF8('5'  ,4053   ,"DIGIT FIVE                                            "),
new ScratchToWarcrafUTF8('6'  ,4054   ,"DIGIT SIX                                             "),
new ScratchToWarcrafUTF8('7'  ,4055   ,"DIGIT SEVEN                                           "),
new ScratchToWarcrafUTF8('8'  ,4056   ,"DIGIT EIGHT                                           "),
new ScratchToWarcrafUTF8('9'  ,4057   ,"DIGIT NINE                                            "),
new ScratchToWarcrafUTF8(':'  ,4058   ,"COLON                                                 "),
new ScratchToWarcrafUTF8(';'  ,4059   ,"SEMICOLON                                             "),
new ScratchToWarcrafUTF8('<'  ,4060   ,"LESS-THAN SIGN                                        "),
new ScratchToWarcrafUTF8('='  ,4061   ,"EQUALS SIGN                                           "),
new ScratchToWarcrafUTF8('>'  ,4062   ,"GREATER-THAN SIGN                                     "),
new ScratchToWarcrafUTF8('?'  ,4063   ,"QUESTION MARK                                         "),
new ScratchToWarcrafUTF8('@'  ,4064   ,"COMMERCIAL AT                                         "),
new ScratchToWarcrafUTF8('A'  ,4065   ,"LATIN CAPITAL LETTER A                                "),
new ScratchToWarcrafUTF8('B'  ,4066   ,"LATIN CAPITAL LETTER B                                "),
new ScratchToWarcrafUTF8('C'  ,4067   ,"LATIN CAPITAL LETTER C                                "),
new ScratchToWarcrafUTF8('D'  ,4068   ,"LATIN CAPITAL LETTER D                                "),
new ScratchToWarcrafUTF8('E'  ,4069   ,"LATIN CAPITAL LETTER E                                "),
new ScratchToWarcrafUTF8('F'  ,4070   ,"LATIN CAPITAL LETTER F                                "),
new ScratchToWarcrafUTF8('G'  ,4071   ,"LATIN CAPITAL LETTER G                                "),
new ScratchToWarcrafUTF8('H'  ,4072   ,"LATIN CAPITAL LETTER H                                "),
new ScratchToWarcrafUTF8('I'  ,4073   ,"LATIN CAPITAL LETTER I                                "),
new ScratchToWarcrafUTF8('J'  ,4074   ,"LATIN CAPITAL LETTER J                                "),
new ScratchToWarcrafUTF8('K'  ,4075   ,"LATIN CAPITAL LETTER K                                "),
new ScratchToWarcrafUTF8('L'  ,4076   ,"LATIN CAPITAL LETTER L                                "),
new ScratchToWarcrafUTF8('M'  ,4077   ,"LATIN CAPITAL LETTER M                                "),
new ScratchToWarcrafUTF8('N'  ,4078   ,"LATIN CAPITAL LETTER N                                "),
new ScratchToWarcrafUTF8('O'  ,4079   ,"LATIN CAPITAL LETTER O                                "),
new ScratchToWarcrafUTF8('P'  ,4080   ,"LATIN CAPITAL LETTER P                                "),
new ScratchToWarcrafUTF8('Q'  ,4081   ,"LATIN CAPITAL LETTER Q                                "),
new ScratchToWarcrafUTF8('R'  ,4082   ,"LATIN CAPITAL LETTER R                                "),
new ScratchToWarcrafUTF8('S'  ,4083   ,"LATIN CAPITAL LETTER S                                "),
new ScratchToWarcrafUTF8('T'  ,4084   ,"LATIN CAPITAL LETTER T                                "),
new ScratchToWarcrafUTF8('U'  ,4085   ,"LATIN CAPITAL LETTER U                                "),
new ScratchToWarcrafUTF8('V'  ,4086   ,"LATIN CAPITAL LETTER V                                "),
new ScratchToWarcrafUTF8('W'  ,4087   ,"LATIN CAPITAL LETTER W                                "),
new ScratchToWarcrafUTF8('X'  ,4088   ,"LATIN CAPITAL LETTER X                                "),
new ScratchToWarcrafUTF8('Y'  ,4089   ,"LATIN CAPITAL LETTER Y                                "),
new ScratchToWarcrafUTF8('Z'  ,4090   ,"LATIN CAPITAL LETTER Z                                "),
new ScratchToWarcrafUTF8('['  ,4091   ,"LEFT SQUARE BRACKET                                   "),
new ScratchToWarcrafUTF8('\\' ,4092   ,"REVERSE SOLIDUS                                       "),
new ScratchToWarcrafUTF8(']'  ,4093   ,"RIGHT SQUARE BRACKET                                  "),
new ScratchToWarcrafUTF8('^'  ,4094   ,"CIRCUMFLEX ACCENT                                     "),
new ScratchToWarcrafUTF8('_'  ,4095   ,"LOW LINE                                              "),
new ScratchToWarcrafUTF8('`'  ,4096   ,"GRAVE ACCENT                                          "),
new ScratchToWarcrafUTF8('a'  ,4097   ,"LATIN SMALL LETTER A                                  "),
new ScratchToWarcrafUTF8('b'  ,4098   ,"LATIN SMALL LETTER B                                  "),
new ScratchToWarcrafUTF8('c'  ,4099   ,"LATIN SMALL LETTER C                                  "),
new ScratchToWarcrafUTF8('d'  ,4100   ,"LATIN SMALL LETTER D                                  "),
new ScratchToWarcrafUTF8('e'  ,4101   ,"LATIN SMALL LETTER E                                  "),
new ScratchToWarcrafUTF8('f'  ,4102   ,"LATIN SMALL LETTER F                                  "),
new ScratchToWarcrafUTF8('g'  ,4103   ,"LATIN SMALL LETTER G                                  "),
new ScratchToWarcrafUTF8('h'  ,4104   ,"LATIN SMALL LETTER H                                  "),
new ScratchToWarcrafUTF8('i'  ,4105   ,"LATIN SMALL LETTER I                                  "),
new ScratchToWarcrafUTF8('j'  ,4106   ,"LATIN SMALL LETTER J                                  "),
new ScratchToWarcrafUTF8('k'  ,4107   ,"LATIN SMALL LETTER K                                  "),
new ScratchToWarcrafUTF8('l'  ,4108   ,"LATIN SMALL LETTER L                                  "),
new ScratchToWarcrafUTF8('m'  ,4109   ,"LATIN SMALL LETTER M                                  "),
new ScratchToWarcrafUTF8('n'  ,4110   ,"LATIN SMALL LETTER N                                  "),
new ScratchToWarcrafUTF8('o'  ,4111   ,"LATIN SMALL LETTER O                                  "),
new ScratchToWarcrafUTF8('p'  ,4112   ,"LATIN SMALL LETTER P                                  "),
new ScratchToWarcrafUTF8('q'  ,4113   ,"LATIN SMALL LETTER Q                                  "),
new ScratchToWarcrafUTF8('r'  ,4114   ,"LATIN SMALL LETTER R                                  "),
new ScratchToWarcrafUTF8('s'  ,4115   ,"LATIN SMALL LETTER S                                  "),
new ScratchToWarcrafUTF8('t'  ,4116   ,"LATIN SMALL LETTER T                                  "),
new ScratchToWarcrafUTF8('u'  ,4117   ,"LATIN SMALL LETTER U                                  "),
new ScratchToWarcrafUTF8('v'  ,4118   ,"LATIN SMALL LETTER V                                  "),
new ScratchToWarcrafUTF8('w'  ,4119   ,"LATIN SMALL LETTER W                                  "),
new ScratchToWarcrafUTF8('x'  ,4120   ,"LATIN SMALL LETTER X                                  "),
new ScratchToWarcrafUTF8('y'  ,4121   ,"LATIN SMALL LETTER Y                                  "),
new ScratchToWarcrafUTF8('z'  ,4122   ,"LATIN SMALL LETTER Z                                  "),
new ScratchToWarcrafUTF8('{'  ,4123   ,"LEFT CURLY BRACKET                                    "),
new ScratchToWarcrafUTF8('|'  ,4124   ,"VERTICAL LINE                                         "),
new ScratchToWarcrafUTF8('}'  ,4125   ,"RIGHT CURLY BRACKET                                   "),
new ScratchToWarcrafUTF8('~'  ,4126   ,"TILDE                                                 "),
new ScratchToWarcrafUTF8(' '   ,4160  ,"NO-BREAK SPACE                                        "),
new ScratchToWarcrafUTF8('¡'  ,4161   ,"INVERTED EXCLAMATION MARK                             "),
new ScratchToWarcrafUTF8('¢'  ,4162   ,"CENT SIGN                                             "),
new ScratchToWarcrafUTF8('£'  ,4163   ,"POUND SIGN                                            "),
new ScratchToWarcrafUTF8('¤'  ,4164   ,"CURRENCY SIGN                                         "),
new ScratchToWarcrafUTF8('¥'  ,4165   ,"YEN SIGN                                              "),
new ScratchToWarcrafUTF8('¦'  ,4166   ,"BROKEN BAR                                            "),
new ScratchToWarcrafUTF8('§'  ,4167   ,"SECTION SIGN                                          "),
new ScratchToWarcrafUTF8('¨'  ,4168   ,"DIAERESIS                                             "),
new ScratchToWarcrafUTF8('©'  ,4169   ,"COPYRIGHT SIGN                                        "),
new ScratchToWarcrafUTF8('ª'  ,4170   ,"FEMININE ORDINAL INDICATOR                            "),
new ScratchToWarcrafUTF8('«'  ,4171   ,"LEFT-POINTING DOUBLE ANGLE QUOTATION MARK             "),
new ScratchToWarcrafUTF8('¬'  ,4172   ,"NOT SIGN                                              "),
new ScratchToWarcrafUTF8(' '   ,4173  ,"SOFT HYPHEN                                           "),
new ScratchToWarcrafUTF8('®'  ,4174   ,"REGISTERED SIGN                                       "),
new ScratchToWarcrafUTF8('¯'  ,4175   ,"MACRON                                                "),
new ScratchToWarcrafUTF8('°'  ,4176   ,"DEGREE SIGN                                           "),
new ScratchToWarcrafUTF8('±'  ,4177   ,"PLUS-MINUS SIGN                                       "),
new ScratchToWarcrafUTF8('²'  ,4178   ,"SUPERSCRIPT TWO                                       "),
new ScratchToWarcrafUTF8('³'  ,4179   ,"SUPERSCRIPT THREE                                     "),
new ScratchToWarcrafUTF8('´'  ,4180   ,"ACUTE ACCENT                                          "),
new ScratchToWarcrafUTF8('µ'  ,4181   ,"MICRO SIGN                                            "),
new ScratchToWarcrafUTF8('¶'  ,4182   ,"PILCROW SIGN                                          "),
new ScratchToWarcrafUTF8('·'  ,4183   ,"MIDDLE DOT                                            "),
new ScratchToWarcrafUTF8('¸'  ,4184   ,"CEDILLA                                               "),
new ScratchToWarcrafUTF8('¹'  ,4185   ,"SUPERSCRIPT ONE                                       "),
new ScratchToWarcrafUTF8('º'  ,4186   ,"MASCULINE ORDINAL INDICATOR                           "),
new ScratchToWarcrafUTF8('»'  ,4187   ,"RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK            "),
new ScratchToWarcrafUTF8('¼'  ,4188   ,"VULGAR FRACTION ONE QUARTER                           "),
new ScratchToWarcrafUTF8('½'  ,4189   ,"VULGAR FRACTION ONE HALF                              "),
new ScratchToWarcrafUTF8('¾'  ,4190   ,"VULGAR FRACTION THREE QUARTERS                        "),
new ScratchToWarcrafUTF8('¿'  ,4191   ,"INVERTED QUESTION MARK                                "),
new ScratchToWarcrafUTF8('À'  ,4192   ,"LATIN CAPITAL LETTER A WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Á'  ,4193   ,"LATIN CAPITAL LETTER A WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Â'  ,4194   ,"LATIN CAPITAL LETTER A WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ã'  ,4195   ,"LATIN CAPITAL LETTER A WITH TILDE                     "),
new ScratchToWarcrafUTF8('Ä'  ,4196   ,"LATIN CAPITAL LETTER A WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Å'  ,4197   ,"LATIN CAPITAL LETTER A WITH RING ABOVE                "),
new ScratchToWarcrafUTF8('Æ'  ,4198   ,"LATIN CAPITAL LETTER AE                               "),
new ScratchToWarcrafUTF8('Ç'  ,4199   ,"LATIN CAPITAL LETTER C WITH CEDILLA                   "),
new ScratchToWarcrafUTF8('È'  ,4200   ,"LATIN CAPITAL LETTER E WITH GRAVE                     "),
new ScratchToWarcrafUTF8('É'  ,4201   ,"LATIN CAPITAL LETTER E WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Ê'  ,4202   ,"LATIN CAPITAL LETTER E WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ë'  ,4203   ,"LATIN CAPITAL LETTER E WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Ì'  ,4204   ,"LATIN CAPITAL LETTER I WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Í'  ,4205   ,"LATIN CAPITAL LETTER I WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Î'  ,4206   ,"LATIN CAPITAL LETTER I WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ï'  ,4207   ,"LATIN CAPITAL LETTER I WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Ð'  ,4208   ,"LATIN CAPITAL LETTER ETH                              "),
new ScratchToWarcrafUTF8('Ñ'  ,4209   ,"LATIN CAPITAL LETTER N WITH TILDE                     "),
new ScratchToWarcrafUTF8('Ò'  ,4210   ,"LATIN CAPITAL LETTER O WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Ó'  ,4211   ,"LATIN CAPITAL LETTER O WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Ô'  ,4212   ,"LATIN CAPITAL LETTER O WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Õ'  ,4213   ,"LATIN CAPITAL LETTER O WITH TILDE                     "),
new ScratchToWarcrafUTF8('Ö'  ,4214   ,"LATIN CAPITAL LETTER O WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('×'  ,4215   ,"MULTIPLICATION SIGN                                   "),
new ScratchToWarcrafUTF8('Ø'  ,4216   ,"LATIN CAPITAL LETTER O WITH STROKE                    "),
new ScratchToWarcrafUTF8('Ù'  ,4217   ,"LATIN CAPITAL LETTER U WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Ú'  ,4218   ,"LATIN CAPITAL LETTER U WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Û'  ,4219   ,"LATIN CAPITAL LETTER U WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ü'  ,4220   ,"LATIN CAPITAL LETTER U WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Ý'  ,4221   ,"LATIN CAPITAL LETTER Y WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Þ'  ,4222   ,"LATIN CAPITAL LETTER THORN                            "),
new ScratchToWarcrafUTF8('ß'  ,4223   ,"LATIN SMALL LETTER SHARP S                            "),
new ScratchToWarcrafUTF8('à'  ,4224   ,"LATIN SMALL LETTER A WITH GRAVE                       "),
new ScratchToWarcrafUTF8('á'  ,4225   ,"LATIN SMALL LETTER A WITH ACUTE                       "),
new ScratchToWarcrafUTF8('â'  ,4226   ,"LATIN SMALL LETTER A WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ã'  ,4227   ,"LATIN SMALL LETTER A WITH TILDE                       "),
new ScratchToWarcrafUTF8('ä'  ,4228   ,"LATIN SMALL LETTER A WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('å'  ,4229   ,"LATIN SMALL LETTER A WITH RING ABOVE                  "),
new ScratchToWarcrafUTF8('æ'  ,4230   ,"LATIN SMALL LETTER AE                                 "),
new ScratchToWarcrafUTF8('ç'  ,4231   ,"LATIN SMALL LETTER C WITH CEDILLA                     "),
new ScratchToWarcrafUTF8('è'  ,4232   ,"LATIN SMALL LETTER E WITH GRAVE                       "),
new ScratchToWarcrafUTF8('é'  ,4233   ,"LATIN SMALL LETTER E WITH ACUTE                       "),
new ScratchToWarcrafUTF8('ê'  ,4234   ,"LATIN SMALL LETTER E WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ë'  ,4235   ,"LATIN SMALL LETTER E WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('ì'  ,4236   ,"LATIN SMALL LETTER I WITH GRAVE                       "),
new ScratchToWarcrafUTF8('í'  ,4237   ,"LATIN SMALL LETTER I WITH ACUTE                       "),
new ScratchToWarcrafUTF8('î'  ,4238   ,"LATIN SMALL LETTER I WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ï'  ,4239   ,"LATIN SMALL LETTER I WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('ð'  ,4240   ,"LATIN SMALL LETTER ETH                                "),
new ScratchToWarcrafUTF8('ñ'  ,4241   ,"LATIN SMALL LETTER N WITH TILDE                       "),
new ScratchToWarcrafUTF8('ò'  ,4242   ,"LATIN SMALL LETTER O WITH GRAVE                       "),
new ScratchToWarcrafUTF8('ó'  ,4243   ,"LATIN SMALL LETTER O WITH ACUTE                       "),
new ScratchToWarcrafUTF8('ô'  ,4244   ,"LATIN SMALL LETTER O WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('õ'  ,4245   ,"LATIN SMALL LETTER O WITH TILDE                       "),
new ScratchToWarcrafUTF8('ö'  ,4246   ,"LATIN SMALL LETTER O WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('÷'  ,4247   ,"DIVISION SIGN                                         "),
new ScratchToWarcrafUTF8('ø'  ,4248   ,"LATIN SMALL LETTER O WITH STROKE                      "),
new ScratchToWarcrafUTF8('ù'  ,4249   ,"LATIN SMALL LETTER U WITH GRAVE                       "),
new ScratchToWarcrafUTF8('ú'  ,4250   ,"LATIN SMALL LETTER U WITH ACUTE                       "),
new ScratchToWarcrafUTF8('û'  ,4251   ,"LATIN SMALL LETTER U WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ü'  ,4252   ,"LATIN SMALL LETTER U WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('ý'  ,4253   ,"LATIN SMALL LETTER Y WITH ACUTE                       "),
new ScratchToWarcrafUTF8('þ'  ,4254   ,"LATIN SMALL LETTER THORN                              "),
new ScratchToWarcrafUTF8('ÿ'  ,4255   ,"LATIN SMALL LETTER Y WITH DIAERESIS	               "),
new ScratchToWarcrafUTF8(' '   ,4032  ,"SPACE                                                 "),
new ScratchToWarcrafUTF8('!'  ,4033   ,"EXCLAMATION MARK                                      "),
new ScratchToWarcrafUTF8('"'  ,4034   ,"QUOTATION MARK                                        "),
new ScratchToWarcrafUTF8('#'  ,4035   ,"NUMBER SIGN                                           "),
new ScratchToWarcrafUTF8('$'  ,4036   ,"DOLLAR SIGN                                           "),
new ScratchToWarcrafUTF8('%'  ,4037   ,"PERCENT SIGN                                          "),
new ScratchToWarcrafUTF8('&'  ,4038   ,"AMPERSAND                                             "),
new ScratchToWarcrafUTF8('\''  ,4039   ,"APOSTROPHE                                            "),
new ScratchToWarcrafUTF8('('  ,4040   ,"LEFT PARENTHESIS                                      "),
new ScratchToWarcrafUTF8(')'  ,4041   ,"RIGHT PARENTHESIS                                     "),
new ScratchToWarcrafUTF8('*'  ,4042   ,"ASTERISK                                              "),
new ScratchToWarcrafUTF8('+'  ,4043   ,"PLUS SIGN                                             "),
new ScratchToWarcrafUTF8(','  ,4044   ,"COMMA                                                 "),
new ScratchToWarcrafUTF8('-'  ,4045   ,"HYPHEN-MINUS                                          "),
new ScratchToWarcrafUTF8('.'  ,4046   ,"FULL STOP                                             "),
new ScratchToWarcrafUTF8('/'  ,4047   ,"SOLIDUS                                               "),
new ScratchToWarcrafUTF8('0'  ,4048   ,"DIGIT ZERO                                            "),
new ScratchToWarcrafUTF8('1'  ,4049   ,"DIGIT ONE                                             "),
new ScratchToWarcrafUTF8('2'  ,4050   ,"DIGIT TWO                                             "),
new ScratchToWarcrafUTF8('3'  ,4051   ,"DIGIT THREE                                           "),
new ScratchToWarcrafUTF8('4'  ,4052   ,"DIGIT FOUR                                            "),
new ScratchToWarcrafUTF8('5'  ,4053   ,"DIGIT FIVE                                            "),
new ScratchToWarcrafUTF8('6'  ,4054   ,"DIGIT SIX                                             "),
new ScratchToWarcrafUTF8('7'  ,4055   ,"DIGIT SEVEN                                           "),
new ScratchToWarcrafUTF8('8'  ,4056   ,"DIGIT EIGHT                                           "),
new ScratchToWarcrafUTF8('9'  ,4057   ,"DIGIT NINE                                            "),
new ScratchToWarcrafUTF8(':'  ,4058   ,"COLON                                                 "),
new ScratchToWarcrafUTF8(';'  ,4059   ,"SEMICOLON                                             "),
new ScratchToWarcrafUTF8('<'  ,4060   ,"LESS-THAN SIGN                                        "),
new ScratchToWarcrafUTF8('='  ,4061   ,"EQUALS SIGN                                           "),
new ScratchToWarcrafUTF8('>'  ,4062   ,"GREATER-THAN SIGN                                     "),
new ScratchToWarcrafUTF8('?'  ,4063   ,"QUESTION MARK                                         "),
new ScratchToWarcrafUTF8('@'  ,4064   ,"COMMERCIAL AT                                         "),
new ScratchToWarcrafUTF8('A'  ,4065   ,"LATIN CAPITAL LETTER A                                "),
new ScratchToWarcrafUTF8('B'  ,4066   ,"LATIN CAPITAL LETTER B                                "),
new ScratchToWarcrafUTF8('C'  ,4067   ,"LATIN CAPITAL LETTER C                                "),
new ScratchToWarcrafUTF8('D'  ,4068   ,"LATIN CAPITAL LETTER D                                "),
new ScratchToWarcrafUTF8('E'  ,4069   ,"LATIN CAPITAL LETTER E                                "),
new ScratchToWarcrafUTF8('F'  ,4070   ,"LATIN CAPITAL LETTER F                                "),
new ScratchToWarcrafUTF8('G'  ,4071   ,"LATIN CAPITAL LETTER G                                "),
new ScratchToWarcrafUTF8('H'  ,4072   ,"LATIN CAPITAL LETTER H                                "),
new ScratchToWarcrafUTF8('I'  ,4073   ,"LATIN CAPITAL LETTER I                                "),
new ScratchToWarcrafUTF8('J'  ,4074   ,"LATIN CAPITAL LETTER J                                "),
new ScratchToWarcrafUTF8('K'  ,4075   ,"LATIN CAPITAL LETTER K                                "),
new ScratchToWarcrafUTF8('L'  ,4076   ,"LATIN CAPITAL LETTER L                                "),
new ScratchToWarcrafUTF8('M'  ,4077   ,"LATIN CAPITAL LETTER M                                "),
new ScratchToWarcrafUTF8('N'  ,4078   ,"LATIN CAPITAL LETTER N                                "),
new ScratchToWarcrafUTF8('O'  ,4079   ,"LATIN CAPITAL LETTER O                                "),
new ScratchToWarcrafUTF8('P'  ,4080   ,"LATIN CAPITAL LETTER P                                "),
new ScratchToWarcrafUTF8('Q'  ,4081   ,"LATIN CAPITAL LETTER Q                                "),
new ScratchToWarcrafUTF8('R'  ,4082   ,"LATIN CAPITAL LETTER R                                "),
new ScratchToWarcrafUTF8('S'  ,4083   ,"LATIN CAPITAL LETTER S                                "),
new ScratchToWarcrafUTF8('T'  ,4084   ,"LATIN CAPITAL LETTER T                                "),
new ScratchToWarcrafUTF8('U'  ,4085   ,"LATIN CAPITAL LETTER U                                "),
new ScratchToWarcrafUTF8('V'  ,4086   ,"LATIN CAPITAL LETTER V                                "),
new ScratchToWarcrafUTF8('W'  ,4087   ,"LATIN CAPITAL LETTER W                                "),
new ScratchToWarcrafUTF8('X'  ,4088   ,"LATIN CAPITAL LETTER X                                "),
new ScratchToWarcrafUTF8('Y'  ,4089   ,"LATIN CAPITAL LETTER Y                                "),
new ScratchToWarcrafUTF8('Z'  ,4090   ,"LATIN CAPITAL LETTER Z                                "),
new ScratchToWarcrafUTF8('['  ,4091   ,"LEFT SQUARE BRACKET                                   "),
new ScratchToWarcrafUTF8('\\' ,4092   ,"REVERSE SOLIDUS                                       "),
new ScratchToWarcrafUTF8(']'  ,4093   ,"RIGHT SQUARE BRACKET                                  "),
new ScratchToWarcrafUTF8('^'  ,4094   ,"CIRCUMFLEX ACCENT                                     "),
new ScratchToWarcrafUTF8('_'  ,4095   ,"LOW LINE                                              "),
new ScratchToWarcrafUTF8('`'  ,4096   ,"GRAVE ACCENT                                          "),
new ScratchToWarcrafUTF8('a'  ,4097   ,"LATIN SMALL LETTER A                                  "),
new ScratchToWarcrafUTF8('b'  ,4098   ,"LATIN SMALL LETTER B                                  "),
new ScratchToWarcrafUTF8('c'  ,4099   ,"LATIN SMALL LETTER C                                  "),
new ScratchToWarcrafUTF8('d'  ,4100   ,"LATIN SMALL LETTER D                                  "),
new ScratchToWarcrafUTF8('e'  ,4101   ,"LATIN SMALL LETTER E                                  "),
new ScratchToWarcrafUTF8('f'  ,4102   ,"LATIN SMALL LETTER F                                  "),
new ScratchToWarcrafUTF8('g'  ,4103   ,"LATIN SMALL LETTER G                                  "),
new ScratchToWarcrafUTF8('h'  ,4104   ,"LATIN SMALL LETTER H                                  "),
new ScratchToWarcrafUTF8('i'  ,4105   ,"LATIN SMALL LETTER I                                  "),
new ScratchToWarcrafUTF8('j'  ,4106   ,"LATIN SMALL LETTER J                                  "),
new ScratchToWarcrafUTF8('k'  ,4107   ,"LATIN SMALL LETTER K                                  "),
new ScratchToWarcrafUTF8('l'  ,4108   ,"LATIN SMALL LETTER L                                  "),
new ScratchToWarcrafUTF8('m'  ,4109   ,"LATIN SMALL LETTER M                                  "),
new ScratchToWarcrafUTF8('n'  ,4110   ,"LATIN SMALL LETTER N                                  "),
new ScratchToWarcrafUTF8('o'  ,4111   ,"LATIN SMALL LETTER O                                  "),
new ScratchToWarcrafUTF8('p'  ,4112   ,"LATIN SMALL LETTER P                                  "),
new ScratchToWarcrafUTF8('q'  ,4113   ,"LATIN SMALL LETTER Q                                  "),
new ScratchToWarcrafUTF8('r'  ,4114   ,"LATIN SMALL LETTER R                                  "),
new ScratchToWarcrafUTF8('s'  ,4115   ,"LATIN SMALL LETTER S                                  "),
new ScratchToWarcrafUTF8('t'  ,4116   ,"LATIN SMALL LETTER T                                  "),
new ScratchToWarcrafUTF8('u'  ,4117   ,"LATIN SMALL LETTER U                                  "),
new ScratchToWarcrafUTF8('v'  ,4118   ,"LATIN SMALL LETTER V                                  "),
new ScratchToWarcrafUTF8('w'  ,4119   ,"LATIN SMALL LETTER W                                  "),
new ScratchToWarcrafUTF8('x'  ,4120   ,"LATIN SMALL LETTER X                                  "),
new ScratchToWarcrafUTF8('y'  ,4121   ,"LATIN SMALL LETTER Y                                  "),
new ScratchToWarcrafUTF8('z'  ,4122   ,"LATIN SMALL LETTER Z                                  "),
new ScratchToWarcrafUTF8('{'  ,4123   ,"LEFT CURLY BRACKET                                    "),
new ScratchToWarcrafUTF8('|'  ,4124   ,"VERTICAL LINE                                         "),
new ScratchToWarcrafUTF8('}'  ,4125   ,"RIGHT CURLY BRACKET                                   "),
new ScratchToWarcrafUTF8('~'  ,4126   ,"TILDE                                                 "),
new ScratchToWarcrafUTF8(' '   ,4160  ,"NO-BREAK SPACE                                        "),
new ScratchToWarcrafUTF8('¡'  ,4161   ,"INVERTED EXCLAMATION MARK                             "),
new ScratchToWarcrafUTF8('¢'  ,4162   ,"CENT SIGN                                             "),
new ScratchToWarcrafUTF8('£'  ,4163   ,"POUND SIGN                                            "),
new ScratchToWarcrafUTF8('¤'  ,4164   ,"CURRENCY SIGN                                         "),
new ScratchToWarcrafUTF8('¥'  ,4165   ,"YEN SIGN                                              "),
new ScratchToWarcrafUTF8('¦'  ,4166   ,"BROKEN BAR                                            "),
new ScratchToWarcrafUTF8('§'  ,4167   ,"SECTION SIGN                                          "),
new ScratchToWarcrafUTF8('¨'  ,4168   ,"DIAERESIS                                             "),
new ScratchToWarcrafUTF8('©'  ,4169   ,"COPYRIGHT SIGN                                        "),
new ScratchToWarcrafUTF8('ª'  ,4170   ,"FEMININE ORDINAL INDICATOR                            "),
new ScratchToWarcrafUTF8('«'  ,4171   ,"LEFT-POINTING DOUBLE ANGLE QUOTATION MARK             "),
new ScratchToWarcrafUTF8('¬'  ,4172   ,"NOT SIGN                                              "),
new ScratchToWarcrafUTF8(' '   ,4173  ,"SOFT HYPHEN                                           "),
new ScratchToWarcrafUTF8('®'  ,4174   ,"REGISTERED SIGN                                       "),
new ScratchToWarcrafUTF8('¯'  ,4175   ,"MACRON                                                "),
new ScratchToWarcrafUTF8('°'  ,4176   ,"DEGREE SIGN                                           "),
new ScratchToWarcrafUTF8('±'  ,4177   ,"PLUS-MINUS SIGN                                       "),
new ScratchToWarcrafUTF8('²'  ,4178   ,"SUPERSCRIPT TWO                                       "),
new ScratchToWarcrafUTF8('³'  ,4179   ,"SUPERSCRIPT THREE                                     "),
new ScratchToWarcrafUTF8('´'  ,4180   ,"ACUTE ACCENT                                          "),
new ScratchToWarcrafUTF8('µ'  ,4181   ,"MICRO SIGN                                            "),
new ScratchToWarcrafUTF8('¶'  ,4182   ,"PILCROW SIGN                                          "),
new ScratchToWarcrafUTF8('·'  ,4183   ,"MIDDLE DOT                                            "),
new ScratchToWarcrafUTF8('¸'  ,4184   ,"CEDILLA                                               "),
new ScratchToWarcrafUTF8('¹'  ,4185   ,"SUPERSCRIPT ONE                                       "),
new ScratchToWarcrafUTF8('º'  ,4186   ,"MASCULINE ORDINAL INDICATOR                           "),
new ScratchToWarcrafUTF8('»'  ,4187   ,"RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK            "),
new ScratchToWarcrafUTF8('¼'  ,4188   ,"VULGAR FRACTION ONE QUARTER                           "),
new ScratchToWarcrafUTF8('½'  ,4189   ,"VULGAR FRACTION ONE HALF                              "),
new ScratchToWarcrafUTF8('¾'  ,4190   ,"VULGAR FRACTION THREE QUARTERS                        "),
new ScratchToWarcrafUTF8('¿'  ,4191   ,"INVERTED QUESTION MARK                                "),
new ScratchToWarcrafUTF8('À'  ,4192   ,"LATIN CAPITAL LETTER A WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Á'  ,4193   ,"LATIN CAPITAL LETTER A WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Â'  ,4194   ,"LATIN CAPITAL LETTER A WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ã'  ,4195   ,"LATIN CAPITAL LETTER A WITH TILDE                     "),
new ScratchToWarcrafUTF8('Ä'  ,4196   ,"LATIN CAPITAL LETTER A WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Å'  ,4197   ,"LATIN CAPITAL LETTER A WITH RING ABOVE                "),
new ScratchToWarcrafUTF8('Æ'  ,4198   ,"LATIN CAPITAL LETTER AE                               "),
new ScratchToWarcrafUTF8('Ç'  ,4199   ,"LATIN CAPITAL LETTER C WITH CEDILLA                   "),
new ScratchToWarcrafUTF8('È'  ,4200   ,"LATIN CAPITAL LETTER E WITH GRAVE                     "),
new ScratchToWarcrafUTF8('É'  ,4201   ,"LATIN CAPITAL LETTER E WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Ê'  ,4202   ,"LATIN CAPITAL LETTER E WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ë'  ,4203   ,"LATIN CAPITAL LETTER E WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Ì'  ,4204   ,"LATIN CAPITAL LETTER I WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Í'  ,4205   ,"LATIN CAPITAL LETTER I WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Î'  ,4206   ,"LATIN CAPITAL LETTER I WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ï'  ,4207   ,"LATIN CAPITAL LETTER I WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Ð'  ,4208   ,"LATIN CAPITAL LETTER ETH                              "),
new ScratchToWarcrafUTF8('Ñ'  ,4209   ,"LATIN CAPITAL LETTER N WITH TILDE                     "),
new ScratchToWarcrafUTF8('Ò'  ,4210   ,"LATIN CAPITAL LETTER O WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Ó'  ,4211   ,"LATIN CAPITAL LETTER O WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Ô'  ,4212   ,"LATIN CAPITAL LETTER O WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Õ'  ,4213   ,"LATIN CAPITAL LETTER O WITH TILDE                     "),
new ScratchToWarcrafUTF8('Ö'  ,4214   ,"LATIN CAPITAL LETTER O WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('×'  ,4215   ,"MULTIPLICATION SIGN                                   "),
new ScratchToWarcrafUTF8('Ø'  ,4216   ,"LATIN CAPITAL LETTER O WITH STROKE                    "),
new ScratchToWarcrafUTF8('Ù'  ,4217   ,"LATIN CAPITAL LETTER U WITH GRAVE                     "),
new ScratchToWarcrafUTF8('Ú'  ,4218   ,"LATIN CAPITAL LETTER U WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Û'  ,4219   ,"LATIN CAPITAL LETTER U WITH CIRCUMFLEX                "),
new ScratchToWarcrafUTF8('Ü'  ,4220   ,"LATIN CAPITAL LETTER U WITH DIAERESIS                 "),
new ScratchToWarcrafUTF8('Ý'  ,4221   ,"LATIN CAPITAL LETTER Y WITH ACUTE                     "),
new ScratchToWarcrafUTF8('Þ'  ,4222   ,"LATIN CAPITAL LETTER THORN                            "),
new ScratchToWarcrafUTF8('ß'  ,4223   ,"LATIN SMALL LETTER SHARP S                            "),
new ScratchToWarcrafUTF8('à'  ,4224   ,"LATIN SMALL LETTER A WITH GRAVE                       "),
new ScratchToWarcrafUTF8('á'  ,4225   ,"LATIN SMALL LETTER A WITH ACUTE                       "),
new ScratchToWarcrafUTF8('â'  ,4226   ,"LATIN SMALL LETTER A WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ã'  ,4227   ,"LATIN SMALL LETTER A WITH TILDE                       "),
new ScratchToWarcrafUTF8('ä'  ,4228   ,"LATIN SMALL LETTER A WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('å'  ,4229   ,"LATIN SMALL LETTER A WITH RING ABOVE                  "),
new ScratchToWarcrafUTF8('æ'  ,4230   ,"LATIN SMALL LETTER AE                                 "),
new ScratchToWarcrafUTF8('ç'  ,4231   ,"LATIN SMALL LETTER C WITH CEDILLA                     "),
new ScratchToWarcrafUTF8('è'  ,4232   ,"LATIN SMALL LETTER E WITH GRAVE                       "),
new ScratchToWarcrafUTF8('é'  ,4233   ,"LATIN SMALL LETTER E WITH ACUTE                       "),
new ScratchToWarcrafUTF8('ê'  ,4234   ,"LATIN SMALL LETTER E WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ë'  ,4235   ,"LATIN SMALL LETTER E WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('ì'  ,4236   ,"LATIN SMALL LETTER I WITH GRAVE                       "),
new ScratchToWarcrafUTF8('í'  ,4237   ,"LATIN SMALL LETTER I WITH ACUTE                       "),
new ScratchToWarcrafUTF8('î'  ,4238   ,"LATIN SMALL LETTER I WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ï'  ,4239   ,"LATIN SMALL LETTER I WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('ð'  ,4240   ,"LATIN SMALL LETTER ETH                                "),
new ScratchToWarcrafUTF8('ñ'  ,4241   ,"LATIN SMALL LETTER N WITH TILDE                       "),
new ScratchToWarcrafUTF8('ò'  ,4242   ,"LATIN SMALL LETTER O WITH GRAVE                       "),
new ScratchToWarcrafUTF8('ó'  ,4243   ,"LATIN SMALL LETTER O WITH ACUTE                       "),
new ScratchToWarcrafUTF8('ô'  ,4244   ,"LATIN SMALL LETTER O WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('õ'  ,4245   ,"LATIN SMALL LETTER O WITH TILDE                       "),
new ScratchToWarcrafUTF8('ö'  ,4246   ,"LATIN SMALL LETTER O WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('÷'  ,4247   ,"DIVISION SIGN                                         "),
new ScratchToWarcrafUTF8('ø'  ,4248   ,"LATIN SMALL LETTER O WITH STROKE                      "),
new ScratchToWarcrafUTF8('ù'  ,4249   ,"LATIN SMALL LETTER U WITH GRAVE                       "),
new ScratchToWarcrafUTF8('ú'  ,4250   ,"LATIN SMALL LETTER U WITH ACUTE                       "),
new ScratchToWarcrafUTF8('û'  ,4251   ,"LATIN SMALL LETTER U WITH CIRCUMFLEX                  "),
new ScratchToWarcrafUTF8('ü'  ,4252   ,"LATIN SMALL LETTER U WITH DIAERESIS                   "),
new ScratchToWarcrafUTF8('ý'  ,4253   ,"LATIN SMALL LETTER Y WITH ACUTE                       "),
new ScratchToWarcrafUTF8('þ'  ,4254   ,"LATIN SMALL LETTER THORN                              "),
new ScratchToWarcrafUTF8('ÿ'  ,4255   ,"LATIN SMALL LETTER Y WITH DIAERESIS                   ")
    };

}
